version: '3.8'

services:
  project_be_app_management:
    container_name: project_be_app_management
    restart: always
    build: .
    expose:
      - "3000"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - SECRET_JWT=${SECRET_JWT}
      - EMAIL_ADMIN=${EMAIL_ADMIN}
      - PASS_ADMIN=${PASS_ADMIN}
      - PORT=3000
      - RATE_LIMIT=${RATE_LIMIT}
    networks:
      - be_app_management_network
      - global_backend_network

  db:
    image: postgres:17.2
    container_name: postgresrbac
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgresrbac:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - be_app_management_network

  be_app_management_nginx:
    image: nginx:1.27.3-alpine-slim
    container_name: be_app_management_nginx
    restart: always
    ports:
      - "3000:80"  # Akses aplikasi di http://localhost:3000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - project_be_app_management
    networks:
      - be_app_management_network
      - global_backend_network

volumes:
  postgresrbac: {}

networks:
  be_app_management_network:
    driver: bridge
  global_backend_network:
    external: true
